### PR TITLE
Add perspective

### PR DESCRIPTION
**Pull request by ts1**
Add `.perspective`

### CODE REVIEW

**Comment by jlmakes** [comment]
Oh yeah, this is cool! Thanks @ts1

**Comment by jlmakes** [comment]
Hey @ts1, I've been troubleshooting some Saucelabs/CI issues — and I've finally got the `development` branch back into shape, but all the rebasing has borked your PR.

I can resolve the merge conflicts, but it's important to me that your contribution shows you as the author, so do you mind rebasing #12 and #13 with the latest `development` ??

**Comment by jlmakes** [comment]
Merged into `0.4.0` thanks @ts1 !

**Comment by ts1** [comment]
Thank you!

**Pull request closed without merging**
